Ibrahim DEV/src/objects/ligne_de_paie__c.object
<CustomObject>
    <fields>
        <fullName>Heure_r__c</fullName>
        <label>Heure realisee</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>poste__c</fullName>
        <label>poste</label>
        <referenceTo>poste__c</referenceTo>
        <relationshipLabel>lignes des paies</relationshipLabel>
        <relationshipName>lignes_des_paies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>semaine__c</fullName>
        <label>semaine</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ligne de paie</label>
    <nameField>
        <label>Nom de ligne de paie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>lignes des paies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Ibrahim DEV/src/objects/poste__c.object
<CustomObject>
    <label>poste</label>
    <nameField>
        <label>Nom de po</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>postes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Ibrahim DEVTEST/src/classes/PDFGeneratorSample.cls
global class PDFGeneratorSample {
 webservice static String GeneratePDF(ID recordID){
        list<ligne_de_paie__c> listp = [select id,semaine__c,poste__c from ligne_de_paie__c
                                        where poste__c =:recordID and Heure_r__c =: 'R' ];
        for(ligne_de_paie__c cc : listp){
        Attachment attach = new Attachment();
        Blob body = Blob.valueOf('');
        attach.Body = body;
        attach.Name = 'sample2.pdf';
        attach.IsPrivate = false;
        attach.ParentId = recordID;
        insert attach;
        }
     list<Attachment> lista = [select id,name from Attachment 
                                        where name =: 'sample.pdf' ];
     String taille = ' la taille est = '+lista.size();
     return taille;
    }

}